# Change these first
owner: oeyoews # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: oeyoew-fun
    url: https://oeyoew.fun
    icon: https://oeyoew.fun/favicon.ico
  - name: oeyoew-fun(bk)
    url: https://oeyoews.github.io/tw5
    icon: https://cdn.jsdelivr.net/gh/oeyoews/img@latest/koi-fish.png
  - name: twm
    url: https://twms.vercel.app
    icon: https://cdn.jsdelivr.net/gh/oeyoews/img@latest/music-notes.png
  - name: upptime
    url: https://oeyoews.github.io/upptime
    icon: https://cdn.jsdelivr.net/gh/oeyoews/img@latest/status.png
  - name: neotw
    url: https://neotw.tiddlyhost.com
    icon: https://gitlab.com/oeyoews/neotw/-/raw/main/images/flask.png
  # - name: test
  #   url: https://nontexist.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname:
  baseUrl: /upptime
  logoUrl: https://cdn.jsdelivr.net/gh/oeyoews/img@latest/status.png
  name: oeyoews
  favicon: https://oeyoew.fun/favicon.ico
  introTitle:
  introMessage:
  navbar:
    - title: 🚦Status
      href: /upptime
    - title: 🏡GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
